### ISSUE TITLE
2.0

### ISSUE THREAD

**Issue by SWSAmor** [tarantool/template#5]
Please would you update to version [2.0](https://github.com/bungle/lua-resty-template/releases/tag/v2.0l) ? template.root, instancing, safe and echo are good features. Thank you.

**Comment by olegrok** [comment]
Hi! Thanks for your issue. I think we should do it. I've prepared a patchset with commits from upstream - https://github.com/tarantool/template/pull/7

Unfortunately, original upstream doesn't contain any tests. It would be great if you test my branch - my tests are passed, but there are very few of them and I can't completely believe them.

**Comment by SWSAmor** [comment]
Thank you. I'm going to test, but need a few days and I don't use the all of the features.
