### ISSUE TITLE
How relative path working?

### ISSUE THREAD

**Issue by SWSAmor** [tarantool/template#6]
I tried many methods. package.path, package.setsearchroot, {{x.htm}}, {{templates/x.htm}} without success. Absolute path is the only way work for me. 
What should i do to relative path work?

**Comment by olegrok** [comment]
package.path, package.setsearchroot are paths where tarantool will search rocks, not templates.

You could find examples of usage relative paths in test - https://github.com/tarantool/template/blob/master/tests/template.lua#L27
Please, consider them. Also I would recommend you check `fio.cwd()` inside your application to make sure that you specify correct path.

**Comment by SWSAmor** [comment]
You're right. The template engine looking the working dir. The working dir was root (/) for me.  So if I want to use relative path or just the template filenames alone i should change the working dir with fio.chdir() to the directory holds the templates in the code before i begin to use templates.

**Comment by olegrok** [comment]
Feel free to reopen / create new issue if you have additional questions
